services:
  backend: 
    build:
      context: ./ai-interview-be
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ai-interview-be:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  frontend:
    build:
      context: ./ai-interviewer-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ai-interviewer-fe:/app
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"